[package]
name = "http"
version = "0.1.0"
authors = ["JeremyWuuuuu <591449570@qq.com>"]
edition = "2018"

[dependencies]
tokio = "0.1.22"
tokio-fs = "0.1.6"
futures = "0.1"
httparse = "1.3.4"
bytes = "0.4.12"
http = "0.1.18"
backtrace = "0.3.35"
